### ISSUE TITLE
KeyError: "Unable to open object (object 'conv1s.0.0.bn.num_batches_tracked' doesn't exist)"

### ISSUE THREAD

**Issue by kevinpzy** [longcw/yolo2-pytorch#100]
Traceback (most recent call last):
  File "demo.py", line 37, in <module>
    net_utils.load_net(trained_model, net)
  File "/home/pcrane/yolo2-pytorch/utils/network.py", line 66, in load_net
    param = torch.from_numpy(np.asarray(h5f[k]))
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/pcrane/anaconda3/lib/python3.6/site-packages/h5py/_hl/group.py", line 167, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object 'conv1s.0.0.bn.num_batches_tracked' doesn't exist)"
![12](https://user-images.githubusercontent.com/23194897/43576842-deb33c3e-967c-11e8-83f9-e21328b57ada.png)
![22](https://user-images.githubusercontent.com/23194897/43576853-e4873e30-967c-11e8-8f71-e36605ee57a3.png)

**Comment by kevinpzy** [comment]
Who can tell me how to solve this issue?Please!

**Comment by bandontseng** [comment]
I found this issue is caused by the pytorch. You can check this commit:
[https://github.com/wuhuikx/pytorch/commit/e2b835d7176d8508876c400c68105d47949c6973](url)

To evade this issue, I downgrade the pytorch , pytorch==py36hdf912b8_0 for anaconda. Or upgrading to the latest version may can fix this issue too, but I haven't tried it yet.

**Comment by mqchen1993** [comment]
I also encountered the same problem. Have you solved it? @kevinpzy

**Comment by wenhaotang** [comment]
I downgraded the pytorch version to 0.4.0 and it worked.

**Comment by maxenceliu** [comment]
In FILE darknet.py Change Line 283
      for i, start in enumerate(range(0, len(keys), 5)):
      for i, start in enumerate(range(0, len(keys), 6)):

**Comment by zhuang5252** [comment]
It is useless to load the model in the retraining, and the loaded model will be commented out.
![image](https://user-images.githubusercontent.com/78992752/183836310-e4f67d7a-bed7-4b4e-b61a-6a032faf4119.png)
