### ISSUE TITLE
No module named 'layers.reorg._ext.reorg_layer._reorg_layer'

### ISSUE THREAD

**Issue by lunasdejavu** [longcw/yolo2-pytorch#116]
I tried python demo under windows7  python 3.6 torch0.4.1 but
it showed the error
Traceback (most recent call last):
  File "demo.py", line 6, in <module>
    from darknet import Darknet19
  File "C:\LPR\yolo2-pytorch\darknet.py", line 8, in <module>
    from layers.reorg.reorg_layer import ReorgLayer
  File "C:\LPR\yolo2-pytorch\layers\reorg\reorg_layer.py", line 3, in <module>
    from ._ext import reorg_layer
  File "C:\LPR\yolo2-pytorch\layers\reorg\_ext\reorg_layer\__init__.py", line 3, in <module>
    from ._reorg_layer import lib as _lib, ffi as _ffi
ModuleNotFoundError: No module named 'layers.reorg._ext.reorg_layer._reorg_layer'

**Comment by 2556004343** [comment]
i had met the same problem ,have you slove it?

**Comment by watermelon476** [comment]
Maybe windows is not suitable.But I had met the same problem in Ubuntu.
