### ISSUE TITLE
own_dict = self.state_dict()   #i can not find its define

### ISSUE THREAD

**Issue by YAyaXM** [longcw/yolo2-pytorch#120]
own_dict = self.state_dict() #  i can not find its define
Traceback (most recent call last):
  File "demo.py", line 37, in <module>
    net_utils.load_net(trained_model, net)
  File "/home/xzm_project/DLpj/yolo/yolo2-pytorch/utils/network.py", line 66, in load_net
    param = torch.from_numpy(np.asarray(h5f[k]))
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/xzm_project/.conda/envs/xzm/lib/python3.6/site-packages/h5py/_hl/group.py", line 167, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object 'conv1s.0.0.bn.num_batches_tracked' doesn't exist)"

**Comment by zhuang5252** [comment]
It is not useful to load the model in the retraining. Just annotate the loaded model.
![image](https://user-images.githubusercontent.com/78992752/183836310-e4f67d7a-bed7-4b4e-b61a-6a032faf4119.png)
