### ISSUE TITLE
ImportError: dynamic module does not define module export function (PyInit_cython_bbox)

### ISSUE THREAD

**Issue by lxtGH** [longcw/yolo2-pytorch#46]
python 3.6
torch 0.3.0
When I run the train.py 
lxt@slave-01:~/pytorch/yolo2-pytorch$ python train.py
Traceback (most recent call last):
  File "train.py", line 8, in <module>
    from darknet import Darknet19
  File "/home/lxt/pytorch/yolo2-pytorch/darknet.py", line 9, in <module>
    from utils.cython_bbox import bbox_ious, bbox_intersections, bbox_overlaps, anchor_intersections
ImportError: dynamic module does not define module export function (PyInit_cython_bbox)

**Comment by luyang-NWPU** [comment]
I get a similar Error (Python2.7):
----------------------------------------------------------------------------------
lu@lu-System-Product-Name:~/yolo2-pytorch-master$ python train.py 
Traceback (most recent call last):
  File "train.py", line 8, in <module>
    from darknet import Darknet19
  File "/home/lu/yolo2-pytorch-master/darknet.py", line 9, in <module>
    from utils.cython_bbox import bbox_ious, bbox_intersections, bbox_overlaps, anchor_intersections
ImportError: No module named cython_bbox

**Comment by longcw** [comment]
You should use absolute import (import from root) or `from .utils.xxx
import xxx` in python3.

2017-12-19 8:58 GMT+08:00 Lu Yang <notifications@github.com>:

**Comment by williamardianto** [comment]
# How to fix this?
Traceback (most recent call last):
  File "/Users/williamardianto/Projects/cv/yolo2-pytorch/demo.py", line 7, in <module>
    from darknet import Darknet19
  File "/Users/williamardianto/Projects/cv/yolo2-pytorch/darknet.py", line 9, in <module>
    from .utils.cython_bbox import bbox_ious, bbox_intersections, bbox_overlaps, anchor_intersections
SystemError: Parent module '' not loaded, cannot perform relative import
