### ISSUE TITLE
ModuleNotFoundError: No module named 'layers.reorg._ext.reorg_layer._reorg_layer'

### ISSUE THREAD

**Issue by happyjin** [longcw/yolo2-pytorch#54]
Hi all:
There is an error when I run: python demo.py

(myenv) lijins-MacBook-Pro:yolo2-pytorch-master lijin$ python demo.py
Traceback (most recent call last):
  File "demo.py", line 6, in <module>
    from darknet import Darknet19
  File "/Users/lijin/Documents/GitHub/RL_tracking/yolo2-pytorch-master/darknet.py", line 8, in <module>
    from layers.reorg.reorg_layer import ReorgLayer
  File "/Users/lijin/Documents/GitHub/RL_tracking/yolo2-pytorch-master/layers/reorg/reorg_layer.py", line 3, in <module>
    from ._ext import reorg_layer
  File "/Users/lijin/Documents/GitHub/RL_tracking/yolo2-pytorch-master/layers/reorg/_ext/reorg_layer/__init__.py", line 3, in <module>
    from ._reorg_layer import lib as _lib, ffi as _ffi
ModuleNotFoundError: No module named 'layers.reorg._ext.reorg_layer._reorg_layer'

Could anyone tell me what is wrong with this error and how to deal with it? Thanks in advance!

**Comment by longcw** [comment]
Did you run `sh make.sh` first?

**Comment by happyjin** [comment]
Yes, I do. But then it comes an error: 'cffi.error.VerificationError: LinkError: command 'gcc' failed with exit status 1'
Could you please tell me how to fix the error and run the code

**Comment by shirishr** [comment]
exact same errors experienced
Ubuntu 16.04 + python 3.6

**Comment by libzzluo** [comment]
The author says:
"2. Build the reorg layer (tf.extract_image_patches)"
then configure the .sh file
the step 2 may miss some necessities.

**Comment by sitongzhen** [comment]
Do you resolve the problem? How to build the reorg layer? Can you tell me? Thank you very much.

**Comment by sheepdnb** [comment]
update on how this problem was solved?

**Comment by EddieEduardo** [comment]
> Did you run `sh make.sh` first?

Can I run in via windows?

**Comment by EddieEduardo** [comment]
> Did you run `sh make.sh`

> Did you run `sh make.sh` first?

Hi,how are you?  You mean that if I want to directly run train.py I also have to run make.sh first ? Cause now I meet up with the seam problem shows that No module named 'layers.reorg._ext.reorg_layer._reorg_layer'.
